[package]
name = "tola-ssg-macros"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Proc macros for tola-ssg"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["derive", "parsing"] }
